spring:
  application:
    name: spreado

  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true        # 기본 true
    locations: classpath:db/migration
    baseline-on-migrate: true   # 기존 DB 위에 적용할 때 유용
    baseline-version: 0

springdoc:
  api-docs:
    enabled: false   # 공통: 기본 꺼두기(운영 안전)
  swagger-ui:
    path: /swagger-ui.html